### ISSUE TITLE
The line with the issue is not correctly printed

### ISSUE THREAD

**Issue by ccostin93** [iwillfailyou/service#15]
### Case 1
```
@Deprecated
public static void someMethod() {
 ... do something
}
```
The above code will print: `filepath > @Deprecated`, instead of the method definition `public static void someMethod() {`

### Case 2
```
/**
* some javadoc
*/
public static void someMethod() {
 ... do something
}
```
The above code will print: `filepath > /**`, instead of the method definition `public static void someMethod() {`

**Comment by ccostin93** [comment]
@nikialeksey For the annotations issue, I created PR: https://github.com/iwillfailyou/java-inspections/pull/11/files

I also played a little for comments, but I got some issues when combining multi-line comment with single-line comments. 
If I have the time, I'll play a little bit more with it :D

**Comment by nikialeksey** [comment]
@ccostin93 Thanks for the issue! Sorry I closed your request, because it needs to be more common solution for other inspections, so I tried to do it in https://github.com/iwillfailyou/java-inspections/pull/14 . You can update the plugin version to `0.1.2` and try it again with such cases. I think, it may be more readable, than that, but let's discuss it in other issues!
